### ISSUE TITLE
Level 3 Dropdown Menu

### ISSUE THREAD

**Issue by Creadecon** [SimonPadbury/b4st#10]
Hey, i really love your Bootstrap 4 Theme, but i can't use Level 3 Menus like this:

Home
Button 1
Button 2
   -Button 2.1
   -Button 2.2
      --Button 2.2.1
      --Button 2.2.2
Button 3

When i use Menus like this, the theme dont show Button 2.2.1 and 2.2.2. How can i fix this?

Greetings from Germany

**Comment by SimonPadbury** [comment]
Hi Creadecon,

Bootstrap 4 navbar accepts the Bootstrap  dropdowns, but the dropdowns only allow level 2 menus. There are no level 3 menu items in Bootstrap, so you would need to engineer these yourself, or maybe find a megamenu plugin, for example. 

First, in header.php you will need to change the wp_nav_menu to have 'depth' => 3 so that you can expose the level 3 menus.

Happy new year,

Simon

**Comment by Creadecon** [comment]
Hey Simon,

oh, thats sad :-( But Thank you for your fast support! :-)

**Comment by SimonPadbury** [comment]
Hi Creadon,

Can you modify this Bootstrap 3 multi-level navbar to be suitable for your needs in Bootstrap 4?

https://codepen.io/ajaypatelaj/pen/prHjD

But — you would still need to expose the level-3 menu items, as in my previous response.

Also, I just found this by Googling (Also Bootstrap 3):  

https://github.com/jeffmould/multi-level-bootstrap-menu/blob/master/wp-bootstrap-navwalker.php

- - - - - - -

Alternatively, if you know enough CSS, maybe you can maybe design your own navbar without using the Bootstrap 4 navbar.

For a completely minimal re-start, try this:

(1.) In your `functions.php`:

```
function register_menu() {
  register_nav_menu('menu', __('Menu'));
}
```

(2.) in your `header.php`:

```
<nav class="my-menu">
    <?php wp_nav_menu( array( 
        'theme_location' => 'menu',
        'depth' => 3,
        'fallback_cb' => '__return_false',
        ) ); 
    ?>
</nav>
```

(3.) Then in your stylesheet, use these classes and add in your own styling:

```
/* Parent: */
.my-menu .menu { }
.my-menu .menu > li { }
.my-menu .menu > li a { }

/* Level 2 (child): */
.my-menu .sub-menu { }
.my-menu .sub-menu > li { }
.my-menu .sub-menu > li a { }

/* Level 3 (grandchild): */
.my-menu .sub-menu > .sub-menu { }
.my-menu .sub-menu > .sub-menu > li { }
.my-menu .sub-menu > .sub-menu > li a { }
```

Here, you are styling these classes added by WordPress itself (targetting them specifically within your `<nav class="my-menu">…</nav>`  wrapper (change "my-menu" to your choice of wrapper class). 

[You don't need to use the nav_walker — that is only for re-building ("extending") the WordPress menu and inserting Bootstrap classes into it.]

Kind regards,

Simon

**Comment by Creadecon** [comment]
Thank you, i will try this next week :-) 👍

**Comment by SimonPadbury** [comment]
You are welcome. 👍
