### ISSUE TITLE
Load Tether before BS JS

### ISSUE THREAD

**Issue by soynatan** [SimonPadbury/b4st#11]
Chrome shows me this error in the console: `Uncaught Error: Bootstrap tooltips require Tether (http://tether.io/)`

It seems to get fixed if you enqueue Tether before Bootstrap JS, in enqueues.php. Like this:

	wp_register_script('tether',  'https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js', false, '1.4.0', true);
	wp_enqueue_script('tether');

	wp_register_script('bootstrap-js', 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js', false, '4.0.0-alpha.6', true);
	wp_enqueue_script('bootstrap-js');

**Comment by SimonPadbury** [comment]
Hi Natán

Thankyou, you are correct. I should have tested this before committing it last time.

**Comment by soynatan** [comment]
Pulling :+1:

Great project!
