### ISSUE TITLE
Error in comment.php

### ISSUE THREAD

**Issue by chinmayrajyaguru** [SimonPadbury/b4st#12]
> Notice: Undefined variable: args in /var/www/example.com/html/wp-content/themes/b4st-master/loops/comments.php on line 27

**Comment by chinmayrajyaguru** [comment]
**Line 27:** `<?php paginate_comments_links( $args ) ?>`

> Add semicolon:   `<?php paginate_comments_links( $args ); ?>`

**Comment by SimonPadbury** [comment]
Thankyou Chinmay

Fixed.

**Comment by chinmayrajyaguru** [comment]
@SimonPadbury Welcome sir! :+1:
