### ISSUE TITLE
siteurl option is deprecated

### ISSUE THREAD

**Issue by khjohnson1972** [SimonPadbury/b4st#16]
"Notice: get_bloginfo was called with an argument that is deprecated since version 2.2.0! The siteurl option is deprecated for the family of bloginfo() functions. Use the url option instead."

See: wp_redirect(get_bloginfo('siteurl').'/404', 404); in loops

Thanks -

**Comment by SimonPadbury** [comment]
Thankyou. Changed `siteurl` to `url` in 4 files.
