### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by khjohnson1972** [SimonPadbury/b4st#17]
If an author has no posts I get a headers already sent error and the redirect never happens. Also, the page stops loading and the footer is never displayed. Thank you -

The error:

Warning: Cannot modify header information - headers already sent by (output started at /var/www/public/wp-content/themes/b4st/header.php:17) in /var/www/public/wp-includes/pluggable.php on line 1195

![2017-05-05 at 11 14 am](https://cloud.githubusercontent.com/assets/2708317/25754265/350006da-3184-11e7-8e9a-e529834609c3.png)

**Comment by SimonPadbury** [comment]
Hi Kevin, 

There must be some trailing whitespace in your code. See:

https://make.wordpress.org/support/handbook/appendix/breakfix-lessons/php-whitespace-headers-already-sent/

BTW, I also made this change (not part of the solution):

Was:

```
<a class="navbar-brand" href="<?php echo home_url('/'); ?>"><?php bloginfo('name'); ?></a>
```

Is changed to:

```
<a class="navbar-brand" href="<?php echo esc_url( home_url('/') ); ?>"><?php bloginfo('name'); ?></a>
```

AND I removed the example logo that was wrapped inside a PHP comment `<?php /* ... */ ?>` in case you were retaining part of it.

Let me know if you're still having an issue.

Simon

**Comment by khjohnson1972** [comment]
Hi Simon:

I did a fresh install, moved the Sample Post to the trash, activated the b4st theme and changed my permalinks to use "Post name."

I then visited the author page at "http://myurl.com/author/myauthorname"

I still get the error (when I elect to display errors):
"Warning: Cannot modify header information - headers already sent by (output started at /var/www/public/wp-content/themes/b4st/header.php:17) in /var/www/public/wp-includes/pluggable.php on line 1195"

When I elect not to show errors, I get the header and no content. I assume that there is some output prior to the redirect.

Not sure what is causing this? When I add the "wp_redirect(get_bloginfo('url').'/404', 404); exit;" to the top of author.php the redirect doesn't work either. I get the response header, "Location: http://myurl.local/404", but the redirect doesn't happen.

Thanks much for your response.

**Comment by SimonPadbury** [comment]
Hi Kevin,

I just added `content-none.php` -- does this fix the problem?

I am not seeing the error.

**Comment by khjohnson1972** [comment]
Hi Simon:

The content-none.php loop was never used. I created a pull request for changes to the author.php file.

The author file now checks if there are posts or not prior to loading the content loop.

Thanks - Kevin

**Comment by SimonPadbury** [comment]
Thanks Kevin,

I just accepted your pull request.

Simon

**Comment by SimonPadbury** [comment]
Thanks again.
