### ISSUE TITLE
Hi why you dont use this theme on wordpress.org?

### ISSUE THREAD

**Issue by htmldiz** [SimonPadbury/b4st#19]
It work nise. But i searching on google and cant find it. Add this template on **wordpress.org**. And your Navbar work. Not pro-inductive. Maybe i can help modify it. If of course you whant modify it.

**Comment by SimonPadbury** [comment]
Hello htmldiz,

b4st is a simple starter theme, with an unusual folder structure (but sensible, in my opinion). It only has the minimum templates required.

But if you think it is good enough to go on wordpress.org <http://wordpress.org/> then maybe I can by uploaded there too.

What modifications to the navbar are necessary? Yes please, submit any improvements.

Simon

**Comment by htmldiz** [comment]
How i can send php file for you?

**Comment by SimonPadbury** [comment]
Either:

(1.) Best option — collaborate directly:  https://help.github.com/articles/editing-files-in-another-user-s-repository/ <https://help.github.com/articles/editing-files-in-another-user-s-repository/>
…….you can create new files in your forked repository of b4st.

Or:

(2.) Send me an email http://simonpadbury.github.io/ <http://simonpadbury.github.io/> 



Simon
