### ISSUE TITLE
Issues with bootstrap navbar

### ISSUE THREAD

**Issue by cefewow** [SimonPadbury/b4st#21]
What i did: http://i.imgur.com/63Ikyos.png  ` (<div class="container">  in nav)`

What i got on mobile: http://i.imgur.com/At7gA4P.png

**Comment by SimonPadbury** [comment]
Hi,

This is not an error in **b4st** -- the problem is with the way BS4 (alpha) _navbar with container inside_ is displayed in Firefox and Crome below width 276px. It is OK in Safari. (I can't check IE/Edge.)

```
/* Fix for container within navbar on small viewports, for Firefox and Chrome.
-- This may but be necessary when Bootstrap 4 is improved after alpha. */

@media (max-width: 575px) {
  .navbar > .container {
    position: static;
    width: 100%;
  }
}
```
I added this CSS above in `theme/css/b4st.css`.

```
<div class="navbar">
  <div class="container>
    ...
  </div>
</div>
```

**Comment by cefewow** [comment]
thanks!

Yep, bs4alpha has a lot of bugs :/
