### ISSUE TITLE
Split post pagination displays the wrong number of pages

### ISSUE THREAD

**Issue by PieterGoossens** [SimonPadbury/b4st#27]
Newer versions of WordPress (at least 4.8.2 does) uses a slightly different markup and wraps the number of pages in a div instead of a paragraph tag at:
 
https://github.com/SimonPadbury/b4st/blob/e19bfffcc3a3966196203aff5955a92543b549c3/functions/split-post-pagination.php#L12

As a result, too many pages are returned. Replacing it with the following line should fix the issue:

```php
$wp_links = trim(str_replace(array('<div class="page-links">Pages: ', '</div>'), '', $wp_links));
```

**Comment by SimonPadbury** [comment]
Hi Pieter,

Thankyou. I have uploaded this fix. Plus I have updated to the newest `Bootstrap-4.0.0beta.2` and `Popper 1.12.3`

> Question on a different subject: do you still use Internet Explorer 11? And do you know Sass? I need help with a problem here: [https://github.com/SimonPadbury/Codebase](https://github.com/SimonPadbury/Codebase) --- IE11 makes a mess of my images within flexbox systems. The biggest problem is with my modals (called "popover").

**Comment by pngoossens** [comment]
Crap... I messed up, sorry about that. The starter theme I'm using (_s) uses a div in paginated posts. The wp_link_pages() function (the one you're using in the b4st theme) uses a paragraph tag by default. 

[https://codex.wordpress.org/Function_Reference/wp_link_pages](url)

**Comment by SimonPadbury** [comment]
OK, I changed it back again.
