### ISSUE TITLE
JavaScript Error: Uncaught TypeError

### ISSUE THREAD

**Issue by richardwo** [SimonPadbury/b4st#28]
Message: Uncaught TypeError: Cannot read property 'fn' of undefined

Steps to reproduce:
Created a new site
cloned the git repo in the themes directory
activated the theme
browsed to home page
saw the message in Chrome developer console

Says it is coming from util.js line 85 so maybe it is something to do with Bootstrap?

**Comment by SimonPadbury** [comment]
Hi Richard,

There is no file called `util.js` in the theme b4st — it is included within `bootstrap.js`

http://getbootstrap.com/docs/4.0/getting-started/javascript/#util <http://getbootstrap.com/docs/4.0/getting-started/javascript/#util>

Sorry I can’t help.

Simon

**Comment by richardwo** [comment]
I've got a fix.
It is something to do with script loading order.
If you edit `b4st/functions/enqueues.php` and replace `wp_enqueue_script( 'jquery' )`

```
	//wp_enqueue_script( 'jquery' );
	wp_register_script('test',  'https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js', false, '1.12.4', true);
	wp_enqueue_script('test');
```
the JavaScript error goes away.
At the moment I've no idea why this would make a difference - if it's coming from a CDN it seems fine and if it's coming from somewhere else there's the error.

**Comment by richardwo** [comment]
Figured it out now
The version of jQuery bundled with WordPress includes an additional line that you don't find when using a CDN:
`jQuery.noConflict();`
That's what is causing the error with Bootstrap.

**Comment by SimonPadbury** [comment]
OK, done.

Except that I linked to https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js -- because I saw that they used this version of jQuery in the Bootstrap docs. I didn't link to the `slim` version, in case developers need the full-fat version.

See http://getbootstrap.com/docs/4.0/getting-started/download/

Let me know if you run into any problems with this.

**Comment by richardwo** [comment]
Thanks.
I've found out that it's actually an issue with Bootstrap 4 Beta 2 (https://github.com/twbs/bootstrap/pull/24530) so when that is released and incorporated into b4st you can restore the enqueues back to how they were.
