### ISSUE TITLE
Responsive menu not working

### ISSUE THREAD

**Issue by DerianAndre** [SimonPadbury/b4st#29]
I can't find why but its now working at least just de JS, chaning manually in DOM to show works.

**Comment by DerianAndre** [comment]
NVM just found the solution:
```
	wp_register_script('jquery-3.2.1', 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js', false, '3.2.1', true);
	wp_enqueue_script('jquery-3.2.1');
```

**Comment by SimonPadbury** [comment]
Hi André,

Thankyou for finding the problem and providing the solution! :-)

I just fixed it.
