### ISSUE TITLE
Breaks with WP 4.5?

### ISSUE THREAD

**Issue by NickGreen** [SimonPadbury/b4st#3]
This theme seems to break when upgrading to WP 4.5. More specifically, the front and back end are whitescreening. When the files for 4.4 are restored, everything works again.  Any chance this isn't the case for other people?

**Comment by SimonPadbury** [comment]
Hi Nick

Sorry, I have been on holiday. I will look into this next week.

Simon

**Comment by SimonPadbury** [comment]
Hi Nick,

I just installed b4st (current version, 1.3) fresh on a local server – Softalicious AMPPS running WordPress 4.5 which I also installed today. Sorry, there are no problems happening for me.

b4st is so minimal, there is barely anything that can go wrong with it.

A quick Googling has shows me that lots of people are having trouble with themes and plugins after WP 4.5 upgrade. I don't know why this is.

Maybe you need to empty your cache. Or maybe disable all your plugins, then refresh your browser (front end) to see whether you can see b4st.

**Comment by NickGreen** [comment]
Thanks for the verification that it isn't causing issues with your basic theme. BTW, we've been using your BS3 starter theme for some time, and have grown partial to it. Thanks for all the hard work.
