### ISSUE TITLE
carousel not working in my local server

### ISSUE THREAD

**Issue by sslakd** [SimonPadbury/b4st#32]
So I copy exactly the code from [here](https://getbootstrap.com/docs/4.0/components/carousel/#carouseldispose)
But in my website, they only show the ACTIVED one and not moving at all. Everything seem fine but they just don't work.

here is my code 

```
<?php get_header(); ?>
<div class="container">
	<div class="row">
		<div class="col-12">
			<img style="width: 100%" src="/dbc/wp-content/themes/b4st-master/theme/css/quote2.png">
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
			  <div class="carousel-inner">
			    <div class="carousel-item active">
			      <img class="d-block w-100" src="/dbc/wp-content/themes/b4st-master/theme/css/marketing-materials.png" alt="First slide">
			    </div>
			    <div class="carousel-item">
			      <img class="d-block w-100" src="/dbc/wp-content/themes/b4st-master/theme/css/change.png" alt="Second slide">
			    </div>
			    <div class="carousel-item">
			      <img class="d-block w-100" src="/dbc/wp-content/themes/b4st-master/theme/css/marketing-materials.png" alt="Third slide">
			    </div>
			  </div>
			  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
			    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
			    <span class="carousel-control-next-icon" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		</div>
	</div>
</div>
<?php get_footer(); ?>
```

**Comment by SimonPadbury** [comment]
Hello Son,

This is working OK: put this in your `index.php` -- in a place where it doesn't break the loop.

```
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="http://via.placeholder.com/1200x600/123456/ffffff?text=Slide+01" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="http://via.placeholder.com/1200x600/996633/ffffff?text=Slide+02" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="http://via.placeholder.com/1200x600/449922/ffffff?text=Slide+03" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
```

I copied this from http://getbootstrap.com/docs/4.0/components/carousel/#with-indicators -- and I added placeholder images from **https://placeholder.com** for testing.

**Comment by sslakd** [comment]
So I create a new template and put those code inside but it still not work for me. Here is code of all page 
`<?php /* Template Name: portfolio */ ?>

<?php get_header(); ?>
<div class="container">
	<div class="row">
		<div class="col-12">
			<img style="width: 100%" src="/dbc/wp-content/themes/b4st-master/theme/css/quote2.png">
		</div>
	</div>
	<div class="row pt-2">
		<div class="col-12">
			  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
			    <ol class="carousel-indicators">
			      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			    </ol>
			    <div class="carousel-inner">
			      <div class="carousel-item active">
			        <img class="d-block w-100" src="http://via.placeholder.com/1200x600/123456/ffffff?text=Slide+01" alt="First slide">
			      </div>
			      <div class="carousel-item">
			        <img class="d-block w-100" src="http://via.placeholder.com/1200x600/996633/ffffff?text=Slide+02" alt="Second slide">
			      </div>
			      <div class="carousel-item">
			        <img class="d-block w-100" src="http://via.placeholder.com/1200x600/449922/ffffff?text=Slide+03" alt="Third slide">
			      </div>
			    </div>
			    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			      <span class="sr-only">Previous</span>
			    </a>
			    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			      <span class="carousel-control-next-icon" aria-hidden="true"></span>
			      <span class="sr-only">Next</span>
			    </a>
			  </div>
		</div>
	</div>
	<div class="row pt-2">
		<div class="col-md-6 col-sm-12 pr-1">
			<div class="row">
				<div class="col-12">
					<img class="img-fluid p-0" style="width: 100%" src="/dbc/wp-content/themes/b4st-master/theme/css/port-marketing.png">
					<div class="position-absolute card-1 transparency">consultation</div>
				</div>
			</div>	
		</div>
		<div class="col-md-6 col-sm-12 pl-1">
			<div class="row">
				<div class="col-12">
					<img class="img-fluid p-0" style="width: 100%" src="/dbc/wp-content/themes/b4st-master/theme/css/port-print.png">
					<div class="position-absolute card-1 transparency">printing services</div>
				</div>
			</div>	
		</div>
	</div>
</div>
<?php get_footer(); ?>
`
Did I do something wrong ?

**Comment by SimonPadbury** [comment]
Hi Son,

When you share big blocks of code, you need to wrap them inside 3 back-ticks, as in this example:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by SimonPadbury** [comment]
I see nothing wrong with your code -- I put it in my theme to test it, and it is working for me. (The only parts I don't get are your images on **your** machine, of course.) Is your `jquery.min.js` and `bootstrap.min.js` getting to the browser OK? E.g., are Bootstrap dropdowns working OK for you?

This is from your message of 5 hours previous -- this is working for me (except that I here comment-out your images that I don't see):

```
<div class="container">

  <!-- [1] your image above the carousel did not show for me, but all this carousel (copied from your message) is working OK: -->

  <div class="row pt-2">
    <div class="col-12">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="http://via.placeholder.com/1200x600/123456/ffffff?text=Slide+01" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="http://via.placeholder.com/1200x600/996633/ffffff?text=Slide+02" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="http://via.placeholder.com/1200x600/449922/ffffff?text=Slide+03" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>

  <!-- [2] your images below the carousel did not show for me -->

</div>
```

**Comment by sslakd** [comment]
Hi,
Thanks for help, I found out the issue, I deleted the ```<?php wp_footer(); ?>```, thought that it is the footer of wordpress, and it cause the problem I had. 
Thanks for your help. I'm really appreciate that! Your work here save me a lot of time. Keep it up!

**Comment by SimonPadbury** [comment]
OK, but somewhere, you still need wp_footer for Wordpress (it is inside the b4st `footer.php`).

**Comment by sslakd** [comment]
yes, i put it back there. Thank man.
