### ISSUE TITLE
 wp_enqueue_script & wp_enqueue_style for "integrity" and "crossorgin" 

### ISSUE THREAD

**Issue by kanlukasz** [SimonPadbury/b4st#33]
Hello, can you add in somehow "integrity" and "crossorgin" for JS and CSS? Is this possible?

**Comment by SimonPadbury** [comment]
Hi,

The re is no easy way to do this, as the capability of adding attributes to enqueued styles/scripts is apparently not in the WordPress Core -- see https://stackoverflow.com/questions/44827134/wordpress-script-with-integrity-and-crossorigin

On that StackOverflow there is a function that may do what you want. I have not tried it, but I will try it when I get some time.

If you can get it to work, please contribute your fix to this `b4st` project.
