### ISSUE TITLE
Loop Includes

### ISSUE THREAD

**Issue by naradas** [SimonPadbury/b4st#37]
Hi Simon,

I really like the way you are separating loops into a different folder. Code looks much more cleaner. 

But in search.php, 

`<?php get_template_part('loops/content', 'search'); ?>`

there is no "content.php" under loops folder, i think it is "search-results.php

`<?php get_template_part('loops/search-results', 'search'); ?>`

Best,

**Comment by SimonPadbury** [comment]
Thankyou Naradas

I just fixed it.

**Comment by SimonPadbury** [comment]
It should be

<?php get_template_part('loops/search-results); ?>
