### ISSUE TITLE
Comment and install script

### ISSUE THREAD

**Issue by markc** [SimonPadbury/b4st#40]
I really appreciate you staying uptodate with Bootstrap v4+ and FontAwesome v5+.

FWIW this script may be useful to others if they want to use the theme directly from Github on a ie; VPS with root perms. It's fairly generic and I think only the WPATH env var needs to be changed to point to where ever the root of the Wordpress install is located...

https://github.com/netserva/sh/blob/master/bin/b4st

I know b4st is only meant to be a starter theme but over time it will be updated so creating new themes as  a child theme still makes sense to me.

Does anyone happen to have an open source modified themes they could share?

**Comment by SimonPadbury** [comment]
Hi Mark

I never learned to use GitHub via the command line, so I don’t know how to implement what you ask. Can you set that up? And maybe add a wiki or another markdown note for instructions to users, if it makes sense to do so.

I put a very minimal child theme tutorial in the b4st wiki.

Simon

**Comment by markc** [comment]
@SimonPadbury thanks for your comment. The only thing I was really asking about is if anyone had any b4st based themes they could share with others, as in open source and perhaps on Github etc. What you have done with b4st is great but there is still a LOT of work needed to create a theme as slick as ie; the simple default twentyseventeen theme. For instance, something as basic as adding a Featured Image to a post is a complete mess. Sure, it's up to me to fix things like that up but seeing there are 50 forks of this project I suspect 25 people have already solved this particular problem. Multiply that by many dozens of other little issues that probably need to be fixed and I'd rather put my efforts towards some "official" child themes that I, and others, can chose from. b4st itself can't be everything to everyone but multiple child themes could satisfy some use cases without the site developer starting from scratch each time they start a new b4st based project.

The use case for my script is someone who has access to a linux based server, commonly a VPS, and wants to simple deploy b4st and a starter child theme to a (or many) virtual host on that server. I just changed the script so that a full path to Wordpress will also work. Usage example would be...
```
wget https://raw.githubusercontent.com/netserva/sh/master/bin/b4st
chmod +x b4st
./b4st
Usage: b4st vhost|path (to base of Wordpress)
```
meaning either `./b4st example.com` (in my case) or `./b4st /var/www/example.com` (for anyone else) will most likely work. Run the script again at some later stage, perhaps on a cron job, and it will update (git pull) from your Github repo. It would not take much to add a second argument to the script to do the same thing for another child theme project on Github as well.

**Comment by danielmrey** [comment]
Hi Mark:

I am working on a B4ST child theme, it is quite basic but adds some bits to the B4ST master:

> Header: Add Meta description + Wrap nav in container + Adds banner image from Feature image
> Functions: Clean some script and styles + Enqueue child style
> Footer: Wrap container in footer + Adds 2 columns for copyrights

Still early days but let me know if you want to give it a look

Daniel.

**Comment by markc** [comment]
@danielmrey  excellent. Yes, I'd like to see what you've done as it's a bit hard to translate words into visual cues. So far all I've done is work on a nicer blog posts listing page using the BS4 media component, which uses flexbox. Two (or more) columns in the footer was going to be my next challenge and then figure out how to modify them via the Customizer like the twentyseventeen theme.

I'll try to get my changes into a Github repo as soon as I have a working posts page, probably called `b4st-child-markc`.

**Comment by danielmrey** [comment]
Hi Mark:

My Child theme is a simple starter b4st child theme.

At the moment I am changing it a lot as the original b4st is changing a lot (Simon in taking on board some of my suggestions and he is adding a lot of changes), so as soon as the b4st is stable I will upload it to Github... also note then I am not very familiar with Github yet so it may take a while but I will keep you posted.

Daniel.

**Comment by markc** [comment]
Unfortunately I am now bumping into these all too often so it looks like I'll just have to make a copy of b4st and work on my own parent theme and manually port updates to the b4st project.
```
PHP Fatal error:  Cannot redeclare b4st_widgets_init()
(previously declared in /home/u/netserva.org/var/www/wp-content/themes/b4st/functions/widgets.php:8)
```

**Comment by SimonPadbury** [comment]
You are bumping into these because b4st was never designed to be a parent theme. You can't redeclare the cinctions because they are not "pluggable".
