### ISSUE TITLE
bootstrap tooltip

### ISSUE THREAD

**Issue by kaplan512** [SimonPadbury/b4st#48]
Hi there. I tried to create bootsrap tooltip according to the documentation https://getbootstrap.com/docs/4.0/components/tooltips/ . So I copy and paste code from documentation and init tooltip in b4st.js and tooltip is working, but options doesn't. For example this don't work

```
$(function () {
  $('[data-toggle="tooltip"]').tooltip({
  	html: true
  })
})
```

Have you tested tooltips?

**Comment by SimonPadbury** [comment]
Hi Kaplan,

I could not get it to work the way you tried. 

> This does not work:
> ```
> // JS
> $(function () {
>  $('[data-toggle="tooltip"]').tooltip({
>  	html: true
>  })
> })
> 
> // HTML
> <button class="btn" data-toggle="tooltip" title="<h1><strong>HTML</strong> inside <code>the</code> <em>tooltip</em></h1>">Hover over me</button>
> ```

But I did get this to work:

```
// JS
$('.btn.example-1').tooltip({
	title: "<h1><strong>HTML</strong> inside <code>the</code> <em>tooltip</em></h1>",
	html: true,
	placement: "bottom"
});

// HTML
<button class="btn example-1">Hover over me</button>
```

My answer is copied (and modified) from https://www.w3schools.com/bootstrap/bootstrap_ref_js_tooltip.asp

(See the "Try it" editor for `html: true`.)

**Comment by kaplan512** [comment]
no, it doesn't work.
have you tested it with the theme?

**Comment by SimonPadbury** [comment]
Yes I have tested it in the theme, as I said yesterday. I got it to work, exactly as in the code above. And it is still working.

Are you reading my reply on GitHub or in your emailer?

Look at the previous email in GitHub. You can copy what I did from there -- or else you can follow the link to w3schools and find another working example there.

**Comment by kaplan512** [comment]
of course, I did it, that's why I'm still here. I don't know why but js doesn't work with tooltips

**Comment by SimonPadbury** [comment]
This is my entire b4st.js -- with the working script (same above) in it:

```
/**!
 * b4st JS
 */

(function ($) {

	'use strict';

	$(document).ready(function() {

		// Comments

		$('.commentlist li').addClass('card');
		$('.comment-reply-link').addClass('btn btn-secondary');

		// Forms

		$('select, input[type=text], input[type=email], input[type=password], textarea').addClass('form-control');
		$('input[type=submit]').addClass('btn btn-primary');

		// Pagination fix for ellipsis

		$('.pagination .dots').addClass('page-link').parent().addClass('disabled');

		// You can put your own code in here

		$('.btn.example-1').tooltip({
			title: "<h1><strong>HTML</strong> inside <code>the</code> <em>tooltip</em></h1>",
			html: true,
			placement: "bottom"
		});
		
	});

}(jQuery));

```

And you can put this anywhere -- in the theme or in a post/page (via the HTML editor):

```
<button class="btn example-1">Hover over me</button>
```

**Comment by kaplan512** [comment]
Yes, sir, I did it maybe three or even more times, result the same

**Comment by SimonPadbury** [comment]
I have a few local installations of WordPress, and these all work: InstantWP, AMPPS (with WordPress) and Bitnami (with WordPress).

Maybe something else in your setup is blocking you. Just trying to guess: is it possible that a XSS attack blocker is in play? A security plugin, or something in controlled by your service provider?

**Comment by kaplan512** [comment]
No, I don't think so. I've just checked this with 3 different sites with your theme and still the same. Sites are on the host, not local

**Comment by SimonPadbury** [comment]
I have a few local installations of WordPress, and these all work: InstantWP, AMPPS (with WordPress) and Bitnami (with WordPress).

Maybe something else in your setup is blocking you. Just trying to guess: is it possible that a XSS attack blocker is in play? A security plugin?

**Comment by SimonPadbury** [comment]
Sorry, there's nothing else I can do. All I know it, it is working form me.

Go to:
https://www.w3schools.com/bootstrap/bootstrap_ref_js_tooltip.asp

And scroll down to see the table of options. then on the row in the table that is for what you require (HTML), click on the button for the "Try it" editor, wherein you will see the example I copied. That opens another window/tab == https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_js_tooltip_html&stacked=h 

Does that example tooltip work for you? Try to copy it, same as I did.

**Comment by kaplan512** [comment]
I did the same like in your previous example. I also tried to do the same with just simple html file and it also worked.  Something wrong when I try to do this with b4st theme. Tooltips works, but js options don't.
And here is bootstrap 3. if I'm right https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_js_tooltip_html&stacked=h

**Comment by SimonPadbury** [comment]
I am sorry you are having so much trouble with this.

I have done all I can do. I can’t replicate the problem that you are having. I do exactly as I have described above and it works OK for me, no problem.

**Comment by SimonPadbury** [comment]
> And here is bootstrap 3. if I'm right https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_js_tooltip_html&stacked=h

Yes but it worked for me in Bootstrap 4.0.0

**Comment by vagu71** [comment]
@kaplan512, faced the same issue, and found out that it was infact jQuery UI that was conflicting with the bootstrap tooltip. Removed that from enqueues and tooltips started working fine.
