### ISSUE TITLE
Page Template

### ISSUE THREAD

**Issue by gurgeng** [SimonPadbury/b4st#5]
What would you recommend/suggest the best method to setup different page templates, or to create different pages, i.e. Home, about, contact, etc

**Comment by SimonPadbury** [comment]
In this basic theme, all Pages use the page template `page.php` and the template_part `loops/content-page.php` (for the page loop).

If you require alternative layouts/classes/styles for some Pages, then you can create either another page template, or another loop. 

In this example below, I will assume you require alternatives for both – but first, be familiar with page templates. e.g. watch this YouTube video (2 years old but still useful):

https://youtu.be/9HCxKyj1SV0

My b4st example:

### Step 1: Create a new page template (e.g. named `page-alt-example.php`) and put it in your b4st root folder.

This below is mostly a copy of `page.php` – with a tag to show you that it is working OK.

```
<?php
/*
 * Template Name: Alternative Page Template
 */
?>

<?php get_header(); ?>

<div class="container">
  
  <span class="tag tag-primary">This is using the alternative page template.</span>
  
  <div class="row">

    <div class="col-sm-8">
      <div id="content" role="main">
        <?php get_template_part('loops/content', 'alt-page'); ?>
      </div><!-- /#content -->
    </div>

    <div class="col-sm-4" id="sidebar" role="navigation">
       <?php get_sidebar(); ?>
    </div>

  </div><!-- /.row -->
</div><!-- /.container -->
```

### Step 2: Create a new loop template_part (e.g. named `content-alt-page.php`) and put it in your b4st `loops/` folder.

This below is mostly a copy of `loops/content-page.php` – with a tag to show you that it is working OK.

```
<?php
/*
The Alternative Page Loop
=========================
*/
?>

<span class="tag tag-success">This is using the alternative page loop.</span>

<?php if(have_posts()): while(have_posts()): the_post(); ?>
    <article role="article" id="post_<?php the_ID()?>" <?php post_class()?>>
        <header>
            <h2><?php the_title()?></h2>
        </header>
        <?php the_content()?>
        <?php wp_link_pages(); ?>
    </article>
<?php endwhile; else: ?>
<?php wp_redirect(get_bloginfo('siteurl').'/404', 404); ?>
<?php exit; ?>
<?php endif; ?>
```

### Step 3: modify these to suit your own design. 

Add in your own classes, styles, etc.
