### ISSUE TITLE
Composer (wpackagist)

### ISSUE THREAD

**Issue by raupie** [SimonPadbury/b4st#53]
Do you have any recommendations on how I could automate the inclusion of the b4st-master into my project through composer or any other means? I'm using composer (wpackagist) to handle my plugins between my different deployment stages. I guess I could technically just manually install it on each server and then leave it alone until an update is made to b4st-master and handle the update manually. Was thinking of just updating composer.json to the new version of b4st-master so it handles updates that way. Thoughts?

**Comment by SimonPadbury** [comment]
Hi Travis,

I have never used Composer, sorry. Call me old fashioned...

**Comment by raupie** [comment]
Looks like this was pretty easy. Might be something to add to the wiki. 

```
{  
    "repositories" : [  
      { 
          "type": "package", 
          "package": { 
              "name": "b4st", 
              "type": "wordpress-theme", 
              "version": "master",
              "source": {
                  "type": "git",
                  "url": "git@github.com:SimonPadbury/b4st.git",
                  "reference": "master"
              }
          }
      }
     ],
     "extra" : {
          "installer-paths" : {
               "wp-content/themes/{$name}/" : ["type:wordpress-theme"]
          }
     },
    "require": {
         "b4st" : "master"
    }
}
```

**Comment by SimonPadbury** [comment]
It will do no harm to folks who don't use Composer -- can you add it to my b4st root directory (if that's where it goes?)

**Comment by raupie** [comment]
Are you sure you would like that included in the root level? It's not a file that adds to the functionality. More of a personal preference on how you want to include b4st into your project. I just started using composer with WordPress, for years I never did. However it's time to leave ftp behind and use git to push changes from local->stage->prod.

**Comment by SimonPadbury** [comment]
OK.

If it's a small job, can you add a b4st wiki page?

**Comment by SimonPadbury** [comment]
Thankyou for adding Composer note to the b4st Wiki — I just saw it.

**Comment by raupie** [comment]
oh sweet! Welcome!

**Comment by SimonPadbury** [comment]
If you’re interested:

https://github.com/SimonPadbury/b4st/wiki/Adding-WooCommerce-support-to-b4st <https://github.com/SimonPadbury/b4st/wiki/Adding-WooCommerce-support-to-b4st>
