### ISSUE TITLE
Cards in card deck not square but elongated

### ISSUE THREAD

**Issue by WCat13** [SimonPadbury/b4st#59]
Hi Simon

I was adding a card deck into the content area and instead of being square something is stretching the height of the cards.
What I expected.
https://codepen.io/WCat/pen/BVzwOE

and what I got.

http://dev.ellecarolinefloraldecor.com/

I have been monkeying around with it for a bit now and just can't seem to figure out what is causing the cards to not display square.

Wondering if you perhaps had some insight or at the very least make you aware of it.

Regards
Wayne

**Comment by philippkanter** [comment]
You have empty <p>-Tags between <div class="card"> and </div>. They cause the white space.

**Comment by WCat13** [comment]
I saw those, Editor seems to be adding them. OK thank you for looking.

**Comment by SimonPadbury** [comment]
Hey, I'm glad you've got this sorted out.

Sorry I was not around in the last week to respond.

**Comment by WCat13** [comment]
No worries. I should have seen that wordpress was adding those p tags. Just never have when visual editor was disabled. Threw me for a loop.

Disabled it with 
`remove_filter( 'the_content', 'wpautop' );`

**Comment by SimonPadbury** [comment]
A WordPress loop. :o)

**Comment by WCat13** [comment]
@SimonPadbury 

Just wanted to make you aware of
https://github.com/maaaaark/bcSwipe
Small script for adding swipe to bootstrap carousels.

**Comment by SimonPadbury** [comment]
Hi,

Thankyou, it looks good.
