### ISSUE TITLE
Do we need "container-responsive" / what's it for

### ISSUE THREAD

**Issue by chunkysteveo** [SimonPadbury/b4st#60]
Hi Simon,

Not so much of an issue, but a question/issue - does the theme need "container-responsive" div class rather than the built in "container" class? As the very first wrapping div for the theme files, it seems odd that it goes against BS4 standards and implements a custom CSS rule to overwrite the "core" container class that everything else works from? I haven't read deep into the issues found from BS4.0 to the latest, but just wanted to check if it was needed anymore as I read up more on BS4?

Thanks in advance,

Steve

**Comment by SimonPadbury** [comment]
Hi Steve,

No need for .container-responsive. I just prefer it and add it to my projects. 

Simon

**Comment by SimonPadbury** [comment]
Want it gone? I will remove it from b4st

**Comment by philippkanter** [comment]
If I'm allowed to get involved:
I like your small powerful theme very much, but I've also deleted the recently added "`responsive`". I partially replaced it with "`fluid`", depending on my use cases.
Maybe you can remove "`responsive`" globally, so that everybody can decide on their own.
Many thanks.

**Comment by SimonPadbury** [comment]
I just removed all container-responsive classes and styles.

**Comment by chunkysteveo** [comment]
Hi Simon,

Thanks for the prompt response. 

That would be great if you have removed. If it did no harm being there then that would be fine - It was more just confusing for people coming to BS4 new (or from BS3 like me) and the very first line was essentially a change in the way it was from BS4 standard. It threw a question mark up straight away before digging further into the theme.

Thanks for the update, that is great that it was not needed, and makes more sense now to not be present. 

Your BS3 theme has been used by me for many years now as a great starting base - and I am in no doubt the B4ST will be used for just as many more!! Keep up the great work, feel free to close this (non)issue.

Cheers,

Steve

**Comment by SimonPadbury** [comment]
OK, good. Job done, I will close the issue.

If you're interested: I currently am working of a BS4 starter theme for Publii.

**Comment by chunkysteveo** [comment]
Never seen Publii till just then! Looks cool - I will keep my eyes peeled for your theme. I'm a core WP dev though, so they would need to try hard to pull me away from my beloved WP! :)

Steve

**Comment by SimonPadbury** [comment]
Just a hobby for me, these days.
