### ISSUE TITLE
Adding affix & scrollspy

### ISSUE THREAD

**Issue by TheaKL** [SimonPadbury/b4st#61]
First off, thank you for the starter theme. Really appreciate seeing a simple, up-to-date Bootstrap theme that's maintained.

My question is, how would I make use of Bootstrap's affix and scrollspy? I'm assuming the affix js is loading with the rest of Bootstrap, so I tried adding the data-spy and data-offset-top attributes in the header.php. Like so:

```
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">

    <a class="navbar-brand" href="<?php echo esc_url( home_url('/') ); ?>"><?php bloginfo('name'); ?></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarDropdown" aria-controls="navbarDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div data-spy="affix" data-offset-top="200" class="collapse navbar-collapse" id="navbarDropdown">
      <?php
        wp_nav_menu( array(
          'theme_location'  => 'navbar',
          'container'       => false,
          'menu_class'      => '',
          'fallback_cb'     => '__return_false',
          'items_wrap'      => '<ul id="%1$s" class="navbar-nav mr-auto mt-2 mt-lg-0 %2$s">%3$s</ul>',
          'depth'           => 2,
          'walker'          => new b4st_walker_nav_menu()
        ) );
      ?>

    </div>

  </div>
</nav>
```

Hoping to have the nav start out at the bottom of the page then affix to the top.

I also tried adding those attributes to the nav. Nothing happens. Is it in the wrong place? Do I need to add some CSS in addition?

Sorry if this is a newb question, this is my first time working with a starter theme. Really enjoying your documentation though!

**Comment by SimonPadbury** [comment]
Hello TheaKL,

[https://getbootstrap.com/docs/4.1/migration/#components](https://getbootstrap.com/docs/4.1/migration/#components) –– this says Bootstrap dropped support for the Affix jQuery plugin in version 4.x, and they now recommend using CSS "position: sticky". Don't forget support for Safari (iPhones etc.):

```
position: -webkit-sticky;
position: sticky;
```

Alternatively, there is a third-party jQuery plugin that can be used in much the same way as the old Bootstrap Affix. You will see it also recommended in the link above, **called ScrollPos-Styler**

Kind regards,

Simon
