### ISSUE TITLE
Font Awesome Optimization (remove font-awesome-config.js & add defer)

### ISSUE THREAD

**Issue by rwilsond** [SimonPadbury/b4st#64]
I think we can remove the font-awesome-config.js file and replace with the script attribute.

The file only has this:
_FontAwesomeConfig = { searchPseudoElements: true };_

Which according to Font Awesome's documentation can be replaced with:
https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#define
_"Use <script data-search-pseudo-elements ... > inside your script tag"_

So if you add my "add_fa_attribute" function to the functions.php file, then it will both:
- Remove the need for the font-awesome-config.js file
- It adds the 'defer' attribute as well, which is recommended by the Font Awesome dev team, per their own example https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=svg-with-js

```php
// =========================================================================
// Add Attributes to FONT AWESOME Script
// =========================================================================
function add_fa_attribute($tag, $handle) {
   $scripts_for_attr = array('font-awesome');
   foreach($scripts_for_attr as $script_for_attr) {
      if ($script_for_attr !== $handle) return $tag;
      return str_replace(' src', ' data-search-pseudo-elements defer src', $tag);
   }
   return $tag;
}
add_filter('script_loader_tag', 'add_fa_attribute', 10, 2);
```

**Comment by SimonPadbury** [comment]
Hi rwilsond,

Thanks, I have now removed the config file. It was unnecessary since b4st now enqueues Font Awesome CSS not JS (there was a time when the CSS was not available on a CDN and so I enqueued the JS and that's when the config file was required for pseudo elements).

And since I'm enqueuing the CSS not JS, I think I don't need your function above.
