### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fmohican** [SimonPadbury/b4st#67]
Hi!
How i can remove that class? `card` from comments? see this https://i.imgur.com/Ko8eSuE.png

**Comment by SimonPadbury** [comment]
Hi Fmohican,

The only places where the WordPress comments are modified by  b4st are in `b4st.js` and `b4st.css`. (The comments PHP itself is that in the WordPress core.)

The `card` class (and the "reply button" classes, `btn btn-primary`) are being injected by the JS.

Other styling (padding, list-style-type: none, etc.) are being done by the CSS.

Delete (or, comment-out) what you don't want in the JS, and then change some paddings in the CSS.

**Comment by fmohican** [comment]
Thanks you very mutch!
