### ISSUE TITLE
Navbar collapse problem

### ISSUE THREAD

**Issue by magsarjav** [SimonPadbury/b4st#72]
Navbar collapse does not work on Android Chrome browser (WP 5.2.3 and b4st current master branch). However, it works fine on desktop browsers when browser window is small (toggle button appears).

**Comment by SimonPadbury** [comment]
Sorry, I have no Android to check this on. Is the B4ST navbar different from Bootstrap 4 somwehere, that may be causing this? Or is the current Bootstrap 4 having the same problem?

**Comment by magsarjav** [comment]
Current Bootstrap 4 works fine on Android. In my opinion, the difference is jQuery version. jquery 1.12.4 is used in wp 5.2 by default, but jquery 3.3.1 is used in recent bootstrap. I think that If I change default jquery version of WP to 3.3.1 or latest, it may cause some errors related to other plugins or wp core.

**Comment by SimonPadbury** [comment]
I have changed the enqueue to obtain jQuery 3.3.1 from a CDN instead of using the older jQuery in the WP core. I think that if somebody's plugin uses an old jQuery, they can enqueue that instead -- or update their plugin.

**Comment by magsarjav** [comment]
Yea, problem has been solved! Thank you. I haven't experienced any conflict between new version of jQuery and WP cores. How about remove one of the duplicated registering scripts at line 28 and 29 in enqueues.php?

**Comment by SimonPadbury** [comment]
Thankyou -- I have just removed that duplication.

**Comment by magsarjav** [comment]
Thank you for quick response
