### ISSUE TITLE
Clarify node version to compile

### ISSUE THREAD

**Issue by kLOsk** [SimonPadbury/b4st#74]
Hi,
Can you help me out which node version is needed to compile. I use 
Node
- lts/erbium -> v12.14.1

Gulp
- [09:39:38] CLI version 3.9.1
- [09:39:38] Local version 4.0.2

and get the following error:

<code>
/Users/klos/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/klos/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129:20
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
</code>
I believe there is some issue with my gulp-cli as the 3.9.1 is the one packaged with gulp, where gulp-cli is now a separate project I believe... anyone can clarify and help out with resolving the issue?

**Comment by kLOsk** [comment]
Ok, switching to node 8.14 (my version i usually run my projects at because they are old...) and doing a npm rebuild and npm install solved the issue now... Still tho, what node version do you guys run this theme at usually?

**Comment by SimonPadbury** [comment]
Hi, I'm currently using Node 13.6.0. But the package.json and gulpfile in B4ST are basically the same as I've used for a few other projects in the last year, while I was on Node 12.whatever.

(Still using Gulp CLI 2.2.0.)

**Comment by kLOsk** [comment]
mhm strange. ye i think i have some misconfig going with node when i dont use 8.14. somehow i always get problems with gulp-cli. with 8.14 i get Gulp CLI 2.2.0. but with other i get  CLI version 3.9.1 which i believe is actually older than 2.2.0 since they made it a separate project... weird. thanks anyways!

**Comment by SimonPadbury** [comment]
If you are in your project folder in the terminal, and you have gulp installed locally in your project, and then input `gulp` — this tells your Gulp CLI to look for your Gulp and then start it.

Whereas, if you are in your project folder in the terminal, and you have gulp installed locally in your project, and then input `npx gulp`, this simply starts your local Gulp (Gulp CLI not involved).

So, you can just use a Gulp installed locally in a project, with no Gulp CLI being installed.
