### ISSUE TITLE
Quick Tutorial: How to enable Bootstrap variable overriding with b4st 3.0 + bootswatch

### ISSUE THREAD

**Issue by kLOsk** [SimonPadbury/b4st#75]
Since b4st 3 is out and @SimonPadbury added gulp compilation to it I wanted to share quick instructions on how to add bs4 via npm and enable variable overriding.

First add bootstrap via npm by running:
`npm install bootstrap`

Then add the following to enqueues.php so we use the npm sourced bootstrap js
<pre>wp_register_script('bootstrap-js', get_template_directory_uri() . '/node_modules/bootstrap/dist/js/bootstrap.min.js', false, '4.4.1', true);
wp_enqueue_script('bootstrap-js');</pre>

and remove the cdn style and js registration:
<pre>//wp_register_style('bootstrap4', 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css', false, '4.4.1', null);
//wp_enqueue_style('bootstrap4');

//wp_register_script('bootstrap4', 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js', false, '4.4.1', true);
//wp_enqueue_script('bootstrap4');</pre>

add to b4st.scss at the top
<pre>
//These are the variables to overwrite bootstrap styling
@import "b4st/variables";

//Load bootstrap style via npm
@import '../../node_modules/bootstrap/scss/bootstrap';
</pre>

add the file variables.scss to b4st folder
<pre>
/* All Bootstrap themeing variables can be added here */

$primary:       #009922;
$enable-shadows:            true;
$enable-gradients:          true;
</pre>

Now you can run gulp and the default bootstrap variables can be overridden.

# Bonus
If you want to use bootswatch themes, that's also easy

Simply run
`npm install bootswatch`
Then change the b4st.scss by adding the two bootswatch scss files (make sure to place them around the bootstrap.scss import call)
<pre>
//we are also adding bootswatch (change [theme] to the theme name)
@import "../../node_modules/dist/[theme]/variables";

//Load bootstrap style via npm
@import '../../node_modules/bootstrap/scss/bootstrap';

//don't forget this
@import "../../node_modules//dist/[theme]/bootswatch";</pre>

**Comment by SimonPadbury** [comment]
All this is good. Can you put it in the Wiki? 

https://github.com/SimonPadbury/b4st/wiki

**Comment by kLOsk** [comment]
sure thing. Not very polished, but here you go:

**Comment by SimonPadbury** [comment]
Thankyou Daniel. I wanted you to add it to the wiki so that you get the kudos, as being the author.

**Comment by kLOsk** [comment]
@SimonPadbury i understand no worries, but what I meant was if you were planning to add this into the project code at some point. Since bootstrap is rather annoying to modify without having access to the scss variables and I guess most users of this project modifying the default styling anyways?

**Comment by nicogaldo** [comment]
Great tutorial! but when I upload the site to the server I would have to include the node_modules folder, just because of bootstrap. Any way to avoid this? The folder weighs 50mb more than it should.

**Comment by kLOsk** [comment]
@nicogaldo instead of using the npm installed bootstrapped you could simply go and download bootstrap from the boostrap site and add the files to your theme folder. then adjust the references for the .js and import scss like so:
<pre>
wp_register_script('bootstrap-js', get_template_directory_uri() . '/bootstrapfolderinyourtheme/bootstrap/dist/js/bootstrap.min.js', false, '4.4.1', true);
@import '../../bootstrapfolderinyourtheme/bootstrap/scss/bootstrap';
</pre>
