### ISSUE TITLE
jQuery Slim causing problems with AJAX

### ISSUE THREAD

**Issue by kLOsk** [SimonPadbury/b4st#76]
Hi Simon,
I noticed you are using the slim version of jQuery three and saw that this is causing a lot of issues with plugins that use AJAX requests. Are you aware of this? Is there a specific reason why you opted for the slim version?

Cheers,
D

**Comment by SimonPadbury** [comment]
I was just copying the Bootstrap website. OK, the fat version is back :-) See this theme v.3.01
