### ISSUE TITLE
Modern Events Caledar plugin not interactive

### ISSUE THREAD

**Issue by geekabit** [SimonPadbury/b4st#77]
Hi,

i have a problem with [Modern Events Calendar](https://webnus.net/modern-events-calendar/).
When i echo one of their shortcodes into a theme file, calendar is being displayed but its just static HTML structure with no data and no interactions.

It looks like it is missing some JS libraries.
wp_head();
and wp_footer(); functions are in the place where they should be - so WTF? What can be a reaon of that ?

Kind regards

**Comment by geekabit** [comment]
nvm. It was a jquery versions confict. Had to delete one.

**Comment by SimonPadbury** [comment]
Thankyou. Anything I deed to do?

**Comment by geekabit** [comment]
@SimonPadbury 
Let me explain a bit more. Problem was bit deeper than i thought at the begining.

- im using [wp bootstrap navwalker](https://github.com/wp-bootstrap/wp-bootstrap-navwalker) with lil customization for purpose of having a  [clickable parent menu item](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/398)
- everything was fine untill i installed Modern Event Calendar which wasnt working corectly cause of jquery conflict. After deleting jQuery enqueue from your theme setup caldera started to work fine BUT parent menu item wasnt clickable again :(
- To solve new problem with menu i had to change JS code described in [398](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/398)
from THIS:
` $('.dropdown-toggle').click(function() { if ($(window).width() > 768) if ($(this).next('.dropdown-menu').is(':visible')) window.location = $(this).attr('href'); });`
to THIS:
`jQuery(function ($) {
    // additional jquery function for WP_NAVWALKER to add clickable parent menu items. 
    $('.dropdown-toggle').click(function() { if ($(window).width() > 768) if ($(this).next('.dropdown-menu').is(':visible')) window.location = $(this).attr('href'); });
})`
otherwise i was getting "$.... is not a function" and calendar or menu wasnt working.

**Comment by SimonPadbury** [comment]
OK, I understand. 

Good that you are making the parent link followable only if the dropdown-menu is visible. Is this working as expected on touch (e.g. iPad landscape; Surface)?

**Comment by geekabit** [comment]
Not yet ;p  Ill post final solution later :)
