### ISSUE TITLE
Cover image block with fixed background

### ISSUE THREAD

**Issue by andymoyle** [SimonPadbury/b4st#80]
In theory this should be full viewport width with parallax effect - the class names on the block sure look like that.
But although the block is full width, the image is exactly half the viewport with and parallax scrolls.
I've tried inspect element adding and removing various background css to try to make the image full width.
The only thing that makes it full width is removing background-attachment:fixed, but then you lose the parallax scroll

Any ideas?

**Comment by SimonPadbury** [comment]
Hi Andy, where's `background-attachment:fixed` coming from? It's not in b4st. Without seeing an example, I would say maybe try `img.size-full {object-fit: cover}`.

**Comment by andymoyle** [comment]
Ugh! It comes from /wp-includes/css/dist/block-library/style.min.css?ver=5.6-alpha-49163

I end up with this markup inside the .entry-content section
```
<div class="wp-block-cover alignfull has-background-dim has-parallax" style="background-image:url(http://localhost/thegatewaychurch/wp-content/uploads/2020/10/IMG_0386-1.png)"><div class="wp-block-cover__inner-container">
<p class="has-text-align-center has-large-font-size"></p>
</div></div>
```

Which has this in the inspector

```
.entry-content>.alignfull, .wp-block-gallery.alignfull, .wp-block-image.alignfull {
    width: 100vw;
    max-width: 100vw;
    margin: 1.5em 0 1.5em 50%;
    -webkit-transform: translateX(-50%);
    transform: translateX(-50%);
}
.wp-block-cover-image.has-background-dim, .wp-block-cover.has-background-dim {
    background-color: #000;
}
.wp-block-cover-image.has-parallax, .wp-block-cover.has-parallax {
    background-attachment: fixed;
}


```
The last two come from wp-includes style sheets for blocks
Swapping background-attachment:fixed for objec-fit:cover - does make it 100vw but loses the parallax.

Stumped and google no help on full-bleed parallax!!!

**Comment by SimonPadbury** [comment]
There's a couple of different ways of doing parallax. Or rather, two different techniques out there both called parallax. Examples, so that you see what I mean:

Simple:
https://codepen.io/tribex/pen/mWNWdz

Complex:
https://keithclark.co.uk/articles/pure-css-parallax-websites/

(Keith Clark is good on his, see his stuff on Codepen.)
